export const lectures = [
  {
    date: "1/22",
    class: "1",
    topic: "Course Intro, Basic Engine Architecture, Camera and Game Loops",
    googleSlides: "https://docs.google.com/presentation/d/1XUIzK4t-KBSompqcti0fThZbQcvcsJvEHcBUbK9KWeQ/edit?usp=sharing",
    codeDemos: "",
  },
  {
    date: "1/29",
    class: "2",
    topic: "Applications and Screens",
    googleSlides: "https://docs.google.com/presentation/d/1ArSOI6GoevVd7yDJ6t4wy14rhHGeHjbE/edit?usp=drive_link&ouid=104255555572779394170&rtpof=true&sd=true",
    codeDemos: "",
  },
  {
    date: "2/5",
    class: "3",
    topic: "Game Worlds, Entity Component System, Collisions Intro",
    googleSlides: "https://docs.google.com/presentation/d/1wCG1-e4uG0IxOFUEZKWBT7Wb7EIpJWA6/edit?usp=sharing&ouid=107401702043394787519&rtpof=true&sd=true",
    codeDemos: "",
  },
  {
    date: "2/12",
    class: "4",
    topic: "Sphere/AAB/Cylinder Collisions",
    googleSlides: "https://docs.google.com/presentation/d/1B2wfdZw76xD3ZVI88ExtCDhWtATSDUG3/edit#slide=id.g208da49415f_0_0",
    codeDemos: "",
  },
  {
    date: "2/19",
    class: "5",
    topic: "Ellipsoid/Triangle Collisions",
    googleSlides: "https://docs.google.com/presentation/d/1vN2xEoel1fT8D3a7efG0p1O6z-cZwlxzyBLbavKYk9A/edit?usp=sharing",
    codeDemos: "",
  },
  {
    date: "2/26",
    class: "",
    topic: "GJK, EPA, and MPR Algorithms",
    googleSlides: "https://docs.google.com/presentation/d/1X5arV3-R21JVZci_cx4tmGSWAotypfqB/edit?usp=sharing&ouid=107401702043394787519&rtpof=true&sd=true",
    codeDemos: "",
  },
  {
    date: "3/12",
    class: "6",
    topic: "Spatial Acceleration Data Structures",
    googleSlides: "https://docs.google.com/presentation/d/1tOqRobg42AouxuCRX7Urh9YhZfYFQHqB/edit?usp=sharing&ouid=107401702043394787519&rtpof=true&sd=true",
    codeDemos: "",
  },
  {
    date: "3/19",
    class: "8",
    topic: "AI and Pathfinding",
    googleSlides: "https://docs.google.com/presentation/d/1Tw9-bxz1QY9Hs4krSroCLMQYPe0_sjOY/edit?usp=sharing&ouid=107401702043394787519&rtpof=true&sd=true",
    codeDemos: "",
  },
  {
    date: "3/26",
    class: "9",
    topic: "🌷 Spring Break - No Class 🌷",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "4/2",
    class: "",
    topic: "Platformer 3 Check-In",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "4/9",
    class: "10",
    topic: "Final Project Topics",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "4/16",
    class: "11",
    topic: "🎮 Q&A with Jordan Tynes 🎮",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "4/23",
    class: "12",
    topic: "👽 Q&A with Mobius Digital 👽",
    googleSlides: "",
    codeDemos: "",

  },
  {
    date: "4/30",
    class: "13",
    topic: "Final Project Check-In",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "5/7",
    class: "14",
    topic: "Final Project Presentations at 5 PM",
    googleSlides: "",
    codeDemos: "",
  },
];
