export const lectures = [
  {
    date: "1/22",
    class: "1",
    topic: "Course Intro, Basic Engine Architecture, Camera and Game Loops",
    googleSlides: "https://docs.google.com/presentation/d/1XUIzK4t-KBSompqcti0fThZbQcvcsJvEHcBUbK9KWeQ/edit?usp=sharing",
    codeDemos: "",
  },
  {
    date: "1/29",
    class: "2",
    topic: "Applications and Screens",
    googleSlides: "https://docs.google.com/presentation/d/1ArSOI6GoevVd7yDJ6t4wy14rhHGeHjbE/edit?usp=drive_link&ouid=104255555572779394170&rtpof=true&sd=true",
    codeDemos: "",
  },
  {
    date: "2/5",
    class: "3",
    topic: "Game Worlds, Entity Component System, Collisions Intro",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "2/12",
    class: "4",
    topic: "Sphere/AAB/Cylinder Collisions, Ellipsoid/Triangle Collisions",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "2/26",
    class: "5",
    topic: "GJK, EPA, and MPR Algorithms",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "3/5",
    class: "",
    topic: "No Lecture - Extra Hours Instead",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "3/12",
    class: "6",
    topic: "Spatial Acceleration Data Structures",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "3/19",
    class: "8",
    topic: "AI and Pathfinding",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "3/26",
    class: "9",
    topic: "🌷 Spring Break - No Class 🌷",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "4/2",
    class: "",
    topic: "Platformer 3 Check-In",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "4/9",
    class: "10",
    topic: "Final Project Topics",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "4/16",
    class: "11",
    topic: "Final Project Check-In 1",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "4/23",
    class: "12",
    topic: "👽 Q&A with Mobius Digital 👽",
    googleSlides: "",
    codeDemos: "",

  },
  {
    date: "4/30",
    class: "13",
    topic: "Final Project Check-In 2",
    googleSlides: "",
    codeDemos: "",
  },
  {
    date: "5/7",
    class: "14",
    topic: "Final Project Presentations at 5 PM",
    googleSlides: "",
    codeDemos: "",
  },
];
