export const lectures = [
  {
    date: "1/21",
    class: "1",
    topic: "Course Intro, Basic Engine Architecture, Camera and Game Loops",
    googleSlides: "https://docs.google.com/presentation/d/1XUIzK4t-KBSompqcti0fThZbQcvcsJvEHcBUbK9KWeQ/edit?usp=sharing",
    zoomRecording: "",
  },
  {
    date: "1/28",
    class: "2",
    topic: "Applications and Screens",
    googleSlides: "https://docs.google.com/presentation/d/1ArSOI6GoevVd7yDJ6t4wy14rhHGeHjbE/edit",
    zoomRecording: "",
  },
  {
    date: "2/4",
    class: "3",
    topic: "Game Worlds, Entity Component System, Collisions Intro",
    googleSlides: "https://docs.google.com/presentation/d/1wCG1-e4uG0IxOFUEZKWBT7Wb7EIpJWA6/edit?usp=sharing&ouid=105263982593318355462&rtpof=true&sd=true",
    zoomRecording: "https://drive.google.com/file/d/16dqkBhGDJqJOMovi_ZvqPPiPhPAMpkRJ/view?usp=sharing",
  },
  {
    date: "2/11",
    class: "4",
    topic: "Ray Casting and Ellipsoid-Triangle Collisions",
    googleSlides: "https://docs.google.com/presentation/d/1B2wfdZw76xD3ZVI88ExtCDhWtATSDUG3/edit?usp=sharing&ouid=105263982593318355462&rtpof=true&sd=true",
    zoomRecording: "https://drive.google.com/file/d/1hQJhgYo_J4e0g8xbxhVgOBgzapQw6AzN/view?usp=drive_link",
  },
  {
    date: "2/18",
    class: "5",
    topic: "GJK/EPA, Rigid Body Physics",
    googleSlides: "https://docs.google.com/presentation/d/1X5arV3-R21JVZci_cx4tmGSWAotypfqB/edit?usp=sharing&ouid=105263982593318355462&rtpof=true&sd=true",
    zoomRecording: "https://drive.google.com/file/d/17lUKvhNH9Z7PWRpbGX1cGAFNKA8FNrE9/view?usp=drive_link",
  },
  {
    date: "2/25",
    class: "6",
    topic: "Animations, Spatial Acceleration Data Structures",
    googleSlides: "",
    zoomRecording:"",
  },
  {
    date: "3/4",
    class: "7",
    topic: "Rendering GPU Optimizations, Final Project Topics",
    googleSlides: "",
  },
  {
    date: "3/11",
    class: "8",
    topic: "Architecture Check, Final Project Ideas",
    googleSlides: "",
  },
  {
    date: "3/18",
    class: "9",
    topic: "Architecture Check, Game Jam!!",
    googleSlides: "",
  },
  {
    date: "3/25",
    class: "10",
    topic: "🌷 Spring Break - No Class 🌷",
    googleSlides: "",
  },
  {
    date: "4/1",
    class: "11",
    topic: "AI and Pathfinding",
    googleSlides: "",
  },
  {
    date: "4/8",
    class: "12",
    topic: "Guest Lectures",
    googleSlides: "",
  },
  {
    date: "4/15",
    class: "13",
    topic: "Guest Lectures",
    googleSlides: "",
  },
  {
    date: "4/22",
    class: "14",
    topic: "Advanced Topics",
    googleSlides: "",
  },
  {
    date: "4/29",
    class: "15",
    topic: "Final Project Check-In",
    googleSlides: "",
  },
  {
    date: "5/6",
    class: "16",
    topic: "Final Project Presentations",
    googleSlides: "",
  },
];
